phase:
  - name: develop
    env:
      - PHASE=develop
      - ENV_VAR="I'm on develop."

  - name: alpha
    env:
      - PHASE=alpha
      - ENV_VAR="I'm on alpha."

  - name: staging
    env:
      - PHASE=staging
      - ENV_VAR="I'm on Staging."

  - name: production
    env:
      - PHASE=production
      - ENV_VAR="I'm on PRODUCTION."