apiVersion: v1
kind: ReplicationController
metadata:
  name: test-dev-controller
spec:
  replicas: 1
  selector:
    app: test
  template:
    metadata:
      labels:
        app: test
        phase: develop
    spec:
      containers:
      - name: test
        image: docker-reg.krane.iwilab.com/cite/test:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          # an http probe
          httpGet:
            path: /_status
            port: 8080
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: test-dev-service
spec:
  selector:
    app: test
    phase: develop
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080