apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-dev-controller
spec:
  replicas: 1
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        phase: dev
    spec:
      containers:
      - name: helloworld
        image: docker-reg.krane.iwilab.com/c8/helloworld
        ports:
        - containerPort: 8080
        livenessProbe:
          # an http probe
          httpGet:
            path: /_status
            port: 8080
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-dev-service
spec:
  selector:
    app: helloworld
    phase: dev
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
